language: objective-c
osx_image: xcode6.4
env: LC_CTYPE=en_US.UTF-8
before_install:
  - gem install xcpretty
install: true
script:
  - set -o pipefail
  - xcodebuild -project GSFileTypeMappings.xcodeproj -scheme GSFileTypeMappings -destination 'platform=iOS Simulator,name=iPhone 6' -sdk iphonesimulator test | xcpretty -c
